import { Inter } from "next/font/google";
import "./globals.css";
import NAVBAR from "./components/navbar/navbar";
import FOOTER from "./components/footer/footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NAVBAR />
        {children}
        <FOOTER />
      </body>
      
    </html>
  );
}
